echo Purging www...
bash ./purge_www.sh
echo Starting jekyll build into gbox_production...
jekyll build --source ./gbox --destination ./gbox_production
echo Copying gbox_production content to web server in /var/www/html...
cp -R ./gbox_production/* /var/www/html
echo Adding other content...
cp -R ./gbox_other/* /var/www/html
echo Adjusting permissions to 755 for www...
chmod -R 755 /var/www

